import type { Vendor } from '@/types/vendors';

export const CALABAR_CARNIVAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    slug: 'mama-calabar-kitchen',
    name: "Mama Calabar's Kitchen",
    description: 'Authentic Calabar cuisine - Edikang Ikong, Afang soup, and fresh seafood',
    category: 'food',
    subcategory: 'Nigerian Cuisine',
    locationName: 'Millennium Park Food Court',
    locationLat: 4.9517,
    locationLng: 8.3417,
    phone: '+234 803 456 7890',
    whatsapp: '+234 803 456 7890',
    operatingHours: {
      monday: { open: '10:00 AM', close: '10:00 PM' },
      tuesday: { open: '10:00 AM', close: '10:00 PM' },
      wednesday: { open: '10:00 AM', close: '10:00 PM' },
      thursday: { open: '10:00 AM', close: '10:00 PM' },
      friday: { open: '10:00 AM', close: '11:00 PM' },
      saturday: { open: '10:00 AM', close: '11:00 PM' },
      sunday: { open: '10:00 AM', close: '10:00 PM' },
    },
    menuItems: [
      { name: 'Edikang Ikong Soup', price: 2500, available: true },
      { name: 'Afang Soup with Eba', price: 2000, available: true },
      { name: 'Fresh Fish Pepper Soup', price: 3000, available: true },
      { name: 'Ekpang Nkukwo', price: 2800, available: true },
    ],
    images: [],
    rating: 4.8,
    reviewCount: 127,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-2',
    slug: 'carnival-drinks-hub',
    name: 'Carnival Drinks Hub',
    description: 'Cold drinks, fresh juice, and local palm wine',
    category: 'drinks',
    subcategory: 'Beverages',
    locationName: 'U.J. Esuene Stadium',
    locationLat: 4.9567,
    locationLng: 8.3467,
    phone: '+234 805 123 4567',
    whatsapp: '+234 805 123 4567',
    operatingHours: {
      monday: { open: '9:00 AM', close: '11:00 PM' },
      friday: { open: '9:00 AM', close: '12:00 AM' },
      saturday: { open: '9:00 AM', close: '12:00 AM' },
      sunday: { open: '9:00 AM', close: '11:00 PM' },
    },
    menuItems: [
      { name: 'Fresh Chapman', price: 800, available: true },
      { name: 'Zobo Drink', price: 500, available: true },
      { name: 'Palm Wine (Fresh)', price: 1000, available: true },
      { name: 'Cold Soft Drinks', price: 300, available: true },
    ],
    images: [],
    rating: 4.5,
    reviewCount: 89,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-3',
    slug: 'african-crafts-corner',
    name: 'African Crafts Corner',
    description: 'Handmade beads, traditional masks, and local artwork',
    category: 'crafts',
    subcategory: 'Handmade',
    locationName: 'Cultural Centre Market',
    locationLat: 4.9497,
    locationLng: 8.3387,
    phone: '+234 807 890 1234',
    whatsapp: '+234 807 890 1234',
    operatingHours: {
      monday: { open: '8:00 AM', close: '8:00 PM' },
      saturday: { open: '8:00 AM', close: '9:00 PM' },
      sunday: { open: '10:00 AM', close: '8:00 PM' },
    },
    menuItems: [
      { name: 'Beaded Necklace', price: 3500, available: true },
      { name: 'Traditional Mask', price: 8000, available: true },
      { name: 'Wooden Sculpture', price: 12000, available: true },
      { name: 'Woven Basket', price: 2500, available: true },
    ],
    images: [],
    rating: 4.7,
    reviewCount: 64,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-4',
    slug: 'carnival-fashion-boutique',
    name: 'Carnival Fashion Boutique',
    description: 'Colorful carnival costumes, traditional attire, and accessories',
    category: 'clothing',
    subcategory: 'Costumes & Fashion',
    locationName: 'Marian Road Shopping District',
    locationLat: 4.9537,
    locationLng: 8.3437,
    phone: '+234 809 234 5678',
    whatsapp: '+234 809 234 5678',
    operatingHours: {
      monday: { open: '9:00 AM', close: '7:00 PM' },
      saturday: { open: '9:00 AM', close: '8:00 PM' },
      sunday: { open: '11:00 AM', close: '6:00 PM' },
    },
    menuItems: [
      { name: 'Carnival Costume (Full Set)', price: 25000, available: true },
      { name: 'Traditional Wrapper', price: 8000, available: true },
      { name: 'Beaded Headpiece', price: 5000, available: true },
      { name: 'Festival T-Shirt', price: 3000, available: true },
    ],
    images: [],
    rating: 4.6,
    reviewCount: 52,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-5',
    slug: 'suya-spot-calabar',
    name: 'Suya Spot Calabar',
    description: 'Best suya in town - beef, chicken, and fish suya with spicy pepper',
    category: 'food',
    subcategory: 'Street Food',
    locationName: 'Murtala Mohammed Highway',
    locationLat: 4.9547,
    locationLng: 8.3397,
    phone: '+234 806 345 6789',
    whatsapp: '+234 806 345 6789',
    operatingHours: {
      monday: { open: '5:00 PM', close: '11:00 PM' },
      friday: { open: '5:00 PM', close: '1:00 AM' },
      saturday: { open: '5:00 PM', close: '1:00 AM' },
      sunday: { open: '5:00 PM', close: '11:00 PM' },
    },
    menuItems: [
      { name: 'Beef Suya (Large)', price: 2000, available: true },
      { name: 'Chicken Suya', price: 2500, available: true },
      { name: 'Fish Suya', price: 3000, available: true },
      { name: 'Suya Combo Platter', price: 5000, available: true },
    ],
    images: [],
    rating: 4.9,
    reviewCount: 203,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-6',
    slug: 'calabar-souvenirs-shop',
    name: 'Calabar Souvenirs Shop',
    description: 'Carnival memorabilia, postcards, keychains, and gift items',
    category: 'souvenirs',
    subcategory: 'Gifts & Memorabilia',
    locationName: 'Millennium Park Entrance',
    locationLat: 4.9527,
    locationLng: 8.3407,
    phone: '+234 808 567 8901',
    whatsapp: '+234 808 567 8901',
    operatingHours: {
      monday: { open: '8:00 AM', close: '9:00 PM' },
      saturday: { open: '8:00 AM', close: '10:00 PM' },
      sunday: { open: '9:00 AM', close: '9:00 PM' },
    },
    menuItems: [
      { name: 'Carnival T-Shirt', price: 3500, available: true },
      { name: 'Calabar Keychain', price: 500, available: true },
      { name: 'Postcard Set (10pcs)', price: 1000, available: true },
      { name: 'Festival Mug', price: 2000, available: true },
    ],
    images: [],
    rating: 4.4,
    reviewCount: 78,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-10-25'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-7',
    slug: 'mobile-phone-charging-station',
    name: 'Mobile Charging Station',
    description: 'Fast phone charging, power banks rental, and mobile accessories',
    category: 'services',
    subcategory: 'Tech Services',
    locationName: 'U.J. Esuene Stadium',
    locationLat: 4.9557,
    locationLng: 8.3457,
    phone: '+234 810 678 9012',
    operatingHours: {
      monday: { open: '8:00 AM', close: '10:00 PM' },
      saturday: { open: '8:00 AM', close: '11:00 PM' },
      sunday: { open: '8:00 AM', close: '10:00 PM' },
    },
    menuItems: [
      { name: 'Phone Charging (30 mins)', price: 200, available: true },
      { name: 'Power Bank Rental (Full Day)', price: 1000, available: true },
      { name: 'Phone Case', price: 1500, available: true },
      { name: 'Charging Cable', price: 800, available: true },
    ],
    images: [],
    rating: 4.3,
    reviewCount: 45,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-8',
    slug: 'face-painting-booth',
    name: 'Face Painting & Body Art',
    description: 'Professional face painting, temporary tattoos, and body glitter',
    category: 'entertainment',
    subcategory: 'Body Art',
    locationName: 'Millennium Park Kids Zone',
    locationLat: 4.9507,
    locationLng: 8.3427,
    phone: '+234 811 789 0123',
    whatsapp: '+234 811 789 0123',
    operatingHours: {
      friday: { open: '12:00 PM', close: '9:00 PM' },
      saturday: { open: '10:00 AM', close: '10:00 PM' },
      sunday: { open: '10:00 AM', close: '9:00 PM' },
    },
    menuItems: [
      { name: 'Face Painting (Simple)', price: 1000, available: true },
      { name: 'Face Painting (Complex)', price: 2000, available: true },
      { name: 'Temporary Tattoo', price: 500, available: true },
      { name: 'Body Glitter Application', price: 1500, available: true },
    ],
    images: [],
    rating: 4.8,
    reviewCount: 91,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-9',
    slug: 'ice-cream-paradise',
    name: 'Ice Cream Paradise',
    description: 'Artisan ice cream, frozen yogurt, and cold treats',
    category: 'food',
    subcategory: 'Desserts',
    locationName: 'Cultural Centre',
    locationLat: 4.9487,
    locationLng: 8.3377,
    phone: '+234 812 890 1234',
    whatsapp: '+234 812 890 1234',
    operatingHours: {
      monday: { open: '11:00 AM', close: '9:00 PM' },
      saturday: { open: '11:00 AM', close: '10:00 PM' },
      sunday: { open: '12:00 PM', close: '9:00 PM' },
    },
    menuItems: [
      { name: 'Single Scoop Ice Cream', price: 800, available: true },
      { name: 'Double Scoop Ice Cream', price: 1500, available: true },
      { name: 'Frozen Yogurt Cup', price: 1200, available: true },
      { name: 'Ice Cream Sundae', price: 2000, available: true },
    ],
    images: [],
    rating: 4.7,
    reviewCount: 112,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-10-30'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-10',
    slug: 'taxi-transport-services',
    name: 'Carnival Taxi Services',
    description: 'Reliable transport to all carnival venues - cars and buses available',
    category: 'services',
    subcategory: 'Transportation',
    locationName: 'Multiple Pickup Points',
    locationLat: 4.9517,
    locationLng: 8.3417,
    phone: '+234 813 901 2345',
    whatsapp: '+234 813 901 2345',
    operatingHours: {
      monday: { open: '6:00 AM', close: '12:00 AM' },
      saturday: { open: '6:00 AM', close: '2:00 AM' },
      sunday: { open: '6:00 AM', close: '12:00 AM' },
    },
    menuItems: [
      { name: 'City Center to Stadium', price: 1500, available: true },
      { name: 'Airport to Hotel', price: 3000, available: true },
      { name: 'Full Day Rental (Car)', price: 25000, available: true },
      { name: 'Group Transport (Bus)', price: 50000, available: true },
    ],
    images: [],
    rating: 4.5,
    reviewCount: 156,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-11',
    slug: 'photography-services',
    name: 'Carnival Memories Photography',
    description: 'Professional photography and instant photo printing',
    category: 'services',
    subcategory: 'Photography',
    locationName: 'Millennium Park Main Stage',
    locationLat: 4.9527,
    locationLng: 8.3417,
    phone: '+234 814 012 3456',
    whatsapp: '+234 814 012 3456',
    operatingHours: {
      friday: { open: '2:00 PM', close: '10:00 PM' },
      saturday: { open: '10:00 AM', close: '11:00 PM' },
      sunday: { open: '10:00 AM', close: '10:00 PM' },
    },
    menuItems: [
      { name: 'Single Photo Print', price: 500, available: true },
      { name: 'Photo Package (5 prints)', price: 2000, available: true },
      { name: 'Professional Photoshoot', price: 10000, available: true },
      { name: 'Group Photo Session', price: 15000, available: true },
    ],
    images: [],
    rating: 4.9,
    reviewCount: 87,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'vendor-12',
    slug: 'traditional-drums-shop',
    name: 'Traditional Drums & Instruments',
    description: 'Authentic African drums, shakers, and musical instruments',
    category: 'crafts',
    subcategory: 'Musical Instruments',
    locationName: 'Cultural Centre Market',
    locationLat: 4.9497,
    locationLng: 8.3387,
    phone: '+234 815 123 4567',
    whatsapp: '+234 815 123 4567',
    operatingHours: {
      monday: { open: '9:00 AM', close: '7:00 PM' },
      saturday: { open: '9:00 AM', close: '8:00 PM' },
      sunday: { open: '11:00 AM', close: '6:00 PM' },
    },
    menuItems: [
      { name: 'Talking Drum', price: 15000, available: true },
      { name: 'Djembe Drum', price: 25000, available: true },
      { name: 'Shekere (Shaker)', price: 5000, available: true },
      { name: 'Wooden Flute', price: 3000, available: true },
    ],
    images: [],
    rating: 4.6,
    reviewCount: 42,
    isVerified: true,
    isActive: true,
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-12-01'),
  },
];
