import type { Hotel } from '@/types';

const now = new Date();

export const CALABAR_CARNIVAL_HOTELS: Hotel[] = [
  {
    id: 'transcorp-hotels-calabar',
    slug: 'transcorp-hotels-calabar',
    name: 'Transcorp Hotels Calabar',
    description:
      'Full-service hotel close to the carnival route with pool, gym and reliable power, popular with visiting bands and crews.',
    address: 'Murtala Mohammed Highway, Calabar, Cross River State',
    locationLat: 4.969,
    locationLng: 8.341,
    phone: '+234-819-XXXX-100',
    email: 'reservations.calabar@transcorphotels.ng',
    website: 'https://www.transcorphotels.com/calabar',
    whatsapp: '+234-819-XXXX-100',
    starRating: 4,
    priceRange: 'mid-range',
    pricePerNightMin: 65000,
    pricePerNightMax: 120000,
    distanceFromCenter: 2.1,
    rating: 4.3,
    reviewCount: 420,
    totalRooms: 146,
    availableRooms: 40,
    amenities: [
      'outdoor pool',
      'fitness centre',
      'on-site restaurant',
      'bar',
      '24/7 power',
      'secure parking',
      'airport shuttle',
    ],
    roomTypes: [
      {
        type: 'Standard Room',
        price: 65000,
        available: 18,
        maxOccupancy: 2,
        amenities: ['king bed', 'air conditioning', 'work desk', 'wifi'],
        images: [],
      },
      {
        type: 'Executive Suite',
        price: 120000,
        available: 8,
        maxOccupancy: 3,
        amenities: ['separate lounge', 'city view', 'premium bedding', 'wifi'],
        images: [],
      },
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '12:00',
      cancellationPolicy: 'Free cancellation up to 48 hours before arrival for standard carnival bookings.',
      additionalInfo: 'Carnival shuttles to Mary Slessor Avenue run every 30 minutes during peak days.',
    },
    images: [
      'https://images.unsplash.com/photo-1745725427804-4d94df0c5eb7?w=800&q=80',
      'https://images.unsplash.com/photo-1731336478850-6bce7235e320?w=800&q=80',
      'https://images.unsplash.com/photo-1609949279531-cf48d64bed89?w=800&q=80',
    ],
    virtualTourUrl: undefined,
    verified: true,
    commissionRate: 0.12,
    carnivalSpecialRate: 10,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'axari-hotel-suites',
    slug: 'axari-hotel-suites',
    name: 'Axari Hotel & Suites',
    description:
      'Comfortable mid-range option just off the carnival corridor, popular with families and small groups.',
    address: 'Murtala Mohammed Highway by Edim Otop, Calabar, Cross River State',
    locationLat: 4.965,
    locationLng: 8.353,
    phone: '+234-803-XXX-7720',
    email: 'stay@axarihotels.com',
    website: 'https://www.axarihotels.com',
    whatsapp: '+234-803-XXX-7720',
    starRating: 3,
    priceRange: 'mid-range',
    pricePerNightMin: 42000,
    pricePerNightMax: 80000,
    distanceFromCenter: 3.4,
    rating: 4.0,
    reviewCount: 210,
    totalRooms: 90,
    availableRooms: 28,
    amenities: ['pool', 'restaurant', 'bar', 'wifi', 'meeting rooms', 'secure parking'],
    roomTypes: [
      {
        type: 'Deluxe Room',
        price: 42000,
        available: 16,
        maxOccupancy: 2,
        amenities: ['queen bed', 'air conditioning', 'wifi'],
        images: [],
      },
      {
        type: 'Family Suite',
        price: 80000,
        available: 6,
        maxOccupancy: 4,
        amenities: ['two bedrooms', 'living area', 'wifi'],
        images: [],
      },
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '11:00',
      cancellationPolicy: 'Carnival reservations require one-night non-refundable deposit.',
      additionalInfo: 'Shuttle service available to key viewing stands on request.',
    },
    images: [
      'https://images.unsplash.com/photo-1610643875911-61395c0d7cf5?w=800&q=80',
      'https://images.unsplash.com/photo-1550567418-1bd5c7712337?w=800&q=80',
    ],
    virtualTourUrl: undefined,
    verified: true,
    commissionRate: 0.1,
    carnivalSpecialRate: 15,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'monty-suites-calabar',
    slug: 'monty-suites-calabar',
    name: 'Monty Suites Calabar',
    description:
      'Suite-style accommodation with spacious rooms and a quiet atmosphere away from the busiest sections of the route.',
    address: 'MCC Road, Ikot Ansa, Calabar, Cross River State',
    locationLat: 4.979,
    locationLng: 8.361,
    phone: '+234-706-XXX-8899',
    email: 'reservations@montysuites.com',
    website: 'https://www.montysuites.com',
    whatsapp: '+234-706-XXX-8899',
    starRating: 4,
    priceRange: 'mid-range',
    pricePerNightMin: 55000,
    pricePerNightMax: 95000,
    distanceFromCenter: 4.8,
    rating: 4.1,
    reviewCount: 160,
    totalRooms: 80,
    availableRooms: 24,
    amenities: ['restaurant', 'bar', 'wifi', 'gym', 'laundry service'],
    roomTypes: [
      {
        type: 'Studio Suite',
        price: 55000,
        available: 14,
        maxOccupancy: 2,
        amenities: ['kitchenette', 'air conditioning', 'wifi'],
        images: [],
      },
      {
        type: 'Executive Suite',
        price: 95000,
        available: 5,
        maxOccupancy: 3,
        amenities: ['separate lounge', 'city view', 'wifi'],
        images: [],
      },
    ],
    policies: {
      checkInTime: '14:00',
      checkOutTime: '12:00',
      cancellationPolicy: 'Flexible rate with free cancellation up to 72 hours before arrival.',
      additionalInfo: 'Good option if you want to retreat from the noise of late-night street parties.',
    },
    images: [
      'https://images.unsplash.com/photo-1759264244746-140bbbc54e1b?w=800&q=80',
      'https://images.unsplash.com/photo-1731336478850-6bce7235e320?w=800&q=80',
    ],
    virtualTourUrl: undefined,
    verified: true,
    commissionRate: 0.1,
    carnivalSpecialRate: undefined,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'marian-road-guest-house',
    slug: 'marian-road-guest-house',
    name: 'Marian Road Guest House',
    description:
      'Budget-friendly guest house within walking distance of parts of the carnival corridor.',
    address: 'Marian Road by IBB Way, Calabar, Cross River State',
    locationLat: 4.960,
    locationLng: 8.327,
    phone: '+234-802-XXX-4420',
    email: undefined,
    website: undefined,
    whatsapp: '+234-802-XXX-4420',
    starRating: 2,
    priceRange: 'budget',
    pricePerNightMin: 18000,
    pricePerNightMax: 30000,
    distanceFromCenter: 1.0,
    rating: 3.7,
    reviewCount: 75,
    totalRooms: 40,
    availableRooms: 12,
    amenities: ['wifi', 'bar', '24/7 power (backup)', 'parking'],
    roomTypes: [
      {
        type: 'Standard Room',
        price: 18000,
        available: 8,
        maxOccupancy: 2,
        amenities: ['double bed', 'fan or AC', 'wifi'],
        images: [],
      },
      {
        type: 'Superior Room',
        price: 25000,
        available: 3,
        maxOccupancy: 2,
        amenities: ['air conditioning', 'fridge', 'wifi'],
        images: [],
      },
    ],
    policies: {
      checkInTime: '13:00',
      checkOutTime: '11:00',
      cancellationPolicy: 'Non-refundable advance payment for peak carnival nights.',
      additionalInfo: 'Great if you want to be able to walk back after late-night street parties.',
    },
    images: [
      'https://images.unsplash.com/photo-1550567418-1bd5c7712337?w=800&q=80',
    ],
    virtualTourUrl: undefined,
    verified: true,
    commissionRate: 0.08,
    carnivalSpecialRate: undefined,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'cicc-lakeside-resort',
    slug: 'cicc-lakeside-resort',
    name: 'CICC Lakeside Resort',
    description:
      'Lakeside resort-style property next to the Calabar International Conference Centre and Tinapa, ideal for guests attending concerts and pageants.',
    address: 'Calabar International Conference Centre, Summit Hills, Calabar',
    locationLat: 4.982,
    locationLng: 8.345,
    phone: '+234-812-XXX-9900',
    email: 'booking@cicclakeside.ng',
    website: undefined,
    whatsapp: '+234-812-XXX-9900',
    starRating: 4,
    priceRange: 'luxury',
    pricePerNightMin: 90000,
    pricePerNightMax: 160000,
    distanceFromCenter: 6.0,
    rating: 4.4,
    reviewCount: 95,
    totalRooms: 110,
    availableRooms: 32,
    amenities: ['lake view', 'pool', 'spa', 'gym', 'conference facilities', 'wifi'],
    roomTypes: [
      {
        type: 'Lake View Room',
        price: 90000,
        available: 20,
        maxOccupancy: 2,
        amenities: ['balcony', 'lake view', 'wifi'],
        images: [],
      },
      {
        type: 'Presidential Suite',
        price: 160000,
        available: 4,
        maxOccupancy: 4,
        amenities: ['separate living area', 'dining space', 'butler service'],
        images: [],
      },
    ],
    policies: {
      checkInTime: '15:00',
      checkOutTime: '12:00',
      cancellationPolicy: 'Premium carnival packages may require full prepayment.',
      additionalInfo: 'Short drive to Miss Africa Calabar and major concert venues.',
    },
    images: [
      'https://images.unsplash.com/photo-1745725427804-4d94df0c5eb7?w=800&q=80',
      'https://images.unsplash.com/photo-1609949279531-cf48d64bed89?w=800&q=80',
      'https://images.unsplash.com/photo-1610643875911-61395c0d7cf5?w=800&q=80',
    ],
    virtualTourUrl: undefined,
    verified: true,
    commissionRate: 0.15,
    carnivalSpecialRate: 20,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

