import type { Event } from '@/types';

// Calabar Carnival 2024 - December 2024
const carnivalYear = 2024;

function makeDate(day: number, hour: number, minute = 0): Date {
  // December (month index 11) in Africa/Lagos local time
  return new Date(carnivalYear, 11, day, hour, minute);
}

export const CALABAR_CARNIVAL_EVENTS: Event[] = [
  {
    id: 'calabar-opening-ceremony',
    slug: 'calabar-opening-ceremony',
    name: 'Calabar Carnival Opening Ceremony & Tree Lighting',
    tagline: 'Kick off a month of colour, music and cultural showcases.',
    description:
      'Official opening of the Calabar Carnival season with performances, speeches, fireworks and the lighting of the Christmas Village.',
    longDescription:
      'Gather with thousands of revellers as Cross River State declares the carnival season open. Expect live performances from local and international acts, fireworks over the skyline and the ceremonial lighting of the Christmas Village.',
    category: 'culture',
    subcategory: 'ceremony',
    tags: ['opening', 'ceremony', 'music', 'culture'],
    venueName: 'Calabar Municipal Garden & Christmas Village',
    venueDescription: 'Central festival hub with main stage, vendors and nightly shows.',
    locationLat: 4.958,
    locationLng: 8.326,
    address: 'Marian Road, Calabar, Cross River State',
    capacity: 15000,
    attendanceCount: 0,
    startTime: makeDate(1, 18, 0),
    endTime: makeDate(1, 22, 0),
    timezone: 'Africa/Lagos',
    featuredImage: 'https://images.unsplash.com/photo-1583166614230-ce6c3a0d20b5?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1583166614230-ce6c3a0d20b5?w=800&q=80',
      'https://images.unsplash.com/photo-1553444664-65312e6cc172?w=800&q=80',
    ],
    videoUrl: undefined,
    liveStreamUrl: undefined,
    organizerId: undefined,
    organizerName: 'Cross River State Carnival Commission',
    isFree: true,
    ticketRequired: false,
    ticketPrice: undefined,
    ticketsAvailable: undefined,
    isFeatured: true,
    isTrending: true,
    isLive: false,
    accessibilityFeatures: ['wheelchair-accessible viewing areas', 'accessible restrooms'],
    amenities: ['food vendors', 'restrooms', 'security', 'medical tent'],
    viewCount: 0,
    saveCount: 0,
    shareCount: 0,
    rating: undefined,
    reviewCount: 0,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'childrens-carnival-parade',
    slug: 'childrens-carnival-parade',
    name: "Children's Carnival Parade",
    tagline: 'Colourful bands of school children take over the route.',
    description:
      'A family-friendly daytime procession where school bands and community groups showcase costumes, choreography and creative themes.',
    longDescription:
      'The Children\'s Carnival Parade brings the next generation of carnival stars to the streets of Calabar. Expect bright costumes, choreographed routines and floats designed by schools and youth groups from across Cross River State.',
    category: 'kids',
    subcategory: 'parade',
    tags: ['kids', 'family', 'parade'],
    venueName: 'Mary Slessor Avenue Carnival Route',
    venueDescription: 'Main carnival route through central Calabar.',
    locationLat: 4.960,
    locationLng: 8.327,
    address: 'Mary Slessor Avenue, Calabar, Cross River State',
    capacity: 20000,
    attendanceCount: 0,
    startTime: makeDate(20, 10, 0),
    endTime: makeDate(20, 15, 0),
    timezone: 'Africa/Lagos',
    featuredImage: 'https://images.unsplash.com/photo-1622831877966-18a6c8731a01?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1622831877966-18a6c8731a01?w=800&q=80',
      'https://images.unsplash.com/photo-1762289711736-f265c93ce1cf?w=800&q=80',
    ],
    videoUrl: undefined,
    liveStreamUrl: undefined,
    organizerId: undefined,
    organizerName: 'Cross River State Carnival Commission',
    isFree: true,
    ticketRequired: false,
    ticketPrice: undefined,
    ticketsAvailable: undefined,
    isFeatured: true,
    isTrending: true,
    isLive: false,
    accessibilityFeatures: ['family viewing areas', 'first-aid stations'],
    amenities: ['restrooms', 'security', 'food vendors'],
    viewCount: 0,
    saveCount: 0,
    shareCount: 0,
    rating: undefined,
    reviewCount: 0,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bikers-carnival',
    slug: 'bikers-carnival',
    name: 'Bikers Carnival & Exotic Car Parade',
    tagline: 'Stunt riders, super bikes and show cars on the carnival route.',
    description:
      'High-energy showcase featuring stunt riders, super bikes and exotic cars cruising through the city with cheering crowds on both sides.',
    longDescription:
      'One of the most anticipated days of the Calabar Carnival, the Bikers Carnival combines stunt displays with a full-scale road parade of bikes and exotic cars. Spectators line the route early to secure the best viewing spots.',
    category: 'sports',
    subcategory: 'parade',
    tags: ['bikers', 'parade', 'nightlife'],
    venueName: 'Millennium Park to Mary Slessor Avenue',
    venueDescription: 'Extended route linking Millennium Park with the main carnival boulevard.',
    locationLat: 4.970,
    locationLng: 8.330,
    address: 'Millennium Park, Calabar, Cross River State',
    capacity: 30000,
    attendanceCount: 0,
    startTime: makeDate(27, 14, 0),
    endTime: makeDate(27, 20, 0),
    timezone: 'Africa/Lagos',
    featuredImage: 'https://images.unsplash.com/photo-1633380010659-e3405204ca8f?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1633380010659-e3405204ca8f?w=800&q=80',
      'https://images.unsplash.com/photo-1633380010612-e42551cbc885?w=800&q=80',
    ],
    videoUrl: undefined,
    liveStreamUrl: undefined,
    organizerId: undefined,
    organizerName: 'Cross River State Carnival Commission',
    isFree: true,
    ticketRequired: false,
    ticketPrice: undefined,
    ticketsAvailable: undefined,
    isFeatured: true,
    isTrending: true,
    isLive: false,
    accessibilityFeatures: ['barriered viewing zones', 'accessible restrooms'],
    amenities: ['food vendors', 'restrooms', 'security', 'medical response teams'],
    viewCount: 0,
    saveCount: 0,
    shareCount: 0,
    rating: undefined,
    reviewCount: 0,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'states-cultural-carnival',
    slug: 'states-cultural-carnival',
    name: 'States Cultural Carnival',
    tagline: 'Nigeria\'s states bring their costumes, dances and heritage to Calabar.',
    description:
      'Colourful cultural troupes from across Nigeria showcase dances, drumming and costumes that celebrate the country\'s diversity.',
    longDescription:
      'The States Cultural Carnival is a showcase of Nigeria\'s cultural wealth, with contingents from different states presenting traditional dances, masquerades and costumes on the streets of Calabar.',
    category: 'culture',
    subcategory: 'parade',
    tags: ['culture', 'parade', 'music'],
    venueName: 'U.J. Esuene Stadium & Mary Slessor Avenue',
    venueDescription: 'Stadium staging area feeding into the main carnival route.',
    locationLat: 4.958,
    locationLng: 8.341,
    address: 'U.J. Esuene Stadium, Calabar, Cross River State',
    capacity: 25000,
    attendanceCount: 0,
    startTime: makeDate(26, 12, 0),
    endTime: makeDate(26, 20, 0),
    timezone: 'Africa/Lagos',
    featuredImage: 'https://images.unsplash.com/photo-1758875913518-7869eb5e1e91?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1758875913518-7869eb5e1e91?w=800&q=80',
      'https://images.unsplash.com/photo-1764670274687-ab62458d6306?w=800&q=80',
    ],
    videoUrl: undefined,
    liveStreamUrl: undefined,
    organizerId: undefined,
    organizerName: 'Cross River State Carnival Commission',
    isFree: true,
    ticketRequired: false,
    ticketPrice: undefined,
    ticketsAvailable: undefined,
    isFeatured: true,
    isTrending: false,
    isLive: false,
    accessibilityFeatures: ['stadium seating options', 'accessible restrooms'],
    amenities: ['stadium seating', 'restrooms', 'security', 'medical teams'],
    viewCount: 0,
    saveCount: 0,
    shareCount: 0,
    rating: undefined,
    reviewCount: 0,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'jean-carnival',
    slug: 'jean-carnival',
    name: 'Jean Carnival & Fashion Parade',
    tagline: 'Denim meets culture in a vibrant fashion showcase.',
    description:
      'A unique fashion-forward carnival event celebrating denim culture with runway shows, street style competitions and creative jean-themed costumes.',
    longDescription:
      'The Jean Carnival brings a contemporary twist to Calabar\'s traditional festivities. Watch as designers, fashion enthusiasts and carnival bands showcase innovative denim creations, from haute couture to street style. The event features runway shows, best-dressed competitions, and a parade of jean-themed floats and costumes that blend traditional African aesthetics with modern denim fashion.',
    category: 'culture',
    subcategory: 'fashion',
    tags: ['fashion', 'parade', 'culture', 'denim'],
    venueName: 'Cultural Centre & Mary Slessor Avenue',
    venueDescription: 'Fashion runway at Cultural Centre with street parade along Mary Slessor Avenue.',
    locationLat: 4.965,
    locationLng: 8.328,
    address: 'Cultural Centre, Calabar, Cross River State',
    capacity: 20000,
    attendanceCount: 0,
    startTime: makeDate(22, 14, 0),
    endTime: makeDate(22, 21, 0),
    timezone: 'Africa/Lagos',
    featuredImage: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
      'https://images.unsplash.com/photo-1558769132-cb1aea1f1c8e?w=800&q=80',
    ],
    videoUrl: undefined,
    liveStreamUrl: undefined,
    organizerId: undefined,
    organizerName: 'Cross River State Carnival Commission',
    isFree: true,
    ticketRequired: false,
    ticketPrice: undefined,
    ticketsAvailable: undefined,
    isFeatured: true,
    isTrending: true,
    isLive: false,
    accessibilityFeatures: ['wheelchair-accessible viewing areas', 'accessible restrooms'],
    amenities: ['fashion vendors', 'food stalls', 'restrooms', 'security', 'photo booths'],
    viewCount: 0,
    saveCount: 0,
    shareCount: 0,
    rating: undefined,
    reviewCount: 0,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'international-carnival-parade',
    slug: 'international-carnival-parade',
    name: 'International Carnival Parade & Street Party',
    tagline: 'Bands from around the world join Calabar\'s biggest street parade.',
    description:
      'The signature Calabar Carnival street parade featuring local bands, international troupes, elaborate floats and late-night street parties.',
    longDescription:
      'Often called Africa\'s Biggest Street Party, the International Carnival Parade closes the season with hours of music, costumes and dancing along Mary Slessor Avenue. Spectator stands, judging points and viewing zones are set up along the full route.',
    category: 'parade',
    subcategory: 'grand parade',
    tags: ['parade', 'international', 'street party'],
    venueName: 'Mary Slessor Avenue Grand Route',
    venueDescription: 'Full carnival route with spectator stands and judging points.',
    locationLat: 4.970,
    locationLng: 8.332,
    address: 'Mary Slessor Avenue, Calabar, Cross River State',
    capacity: 50000,
    attendanceCount: 0,
    startTime: makeDate(28, 12, 0),
    endTime: makeDate(29, 2, 0),
    timezone: 'Africa/Lagos',
    featuredImage: 'https://images.unsplash.com/photo-1761774805205-1707c369cae9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1761774805205-1707c369cae9?w=800&q=80',
      'https://images.unsplash.com/photo-1742295301784-eb8a71c25c2d?w=800&q=80',
    ],
    videoUrl: undefined,
    liveStreamUrl: undefined,
    organizerId: undefined,
    organizerName: 'Cross River State Carnival Commission',
    isFree: true,
    ticketRequired: false,
    ticketPrice: undefined,
    ticketsAvailable: undefined,
    isFeatured: true,
    isTrending: true,
    isLive: false,
    accessibilityFeatures: ['accessible viewing bays', 'priority support points'],
    amenities: ['food courts', 'restrooms', 'security', 'medical response'],
    viewCount: 0,
    saveCount: 0,
    shareCount: 0,
    rating: undefined,
    reviewCount: 0,
    status: 'upcoming',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

