import type { Band } from '@/types/carnival';

// Calabar Carnival 2025 Bands
const carnivalYear = 2025;

export const CALABAR_CARNIVAL_BANDS: Band[] = [
  {
    id: 'seagulls-band',
    name: 'Seagulls Band',
    description: 'The legendary Seagulls Band returns with a spectacular ocean-themed performance featuring flowing blue costumes, wave-inspired choreography, and maritime cultural elements.',
    theme: 'Ocean Majesty',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'passion-4-band',
    name: 'Passion 4 Band',
    description: 'Known for their fiery performances and vibrant red costumes, Passion 4 brings energy and excitement with Afrobeat rhythms and contemporary dance moves.',
    theme: 'Fire & Passion',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bayside-band',
    name: 'Bayside Band',
    description: 'Celebrating Calabar\'s coastal heritage, Bayside Band showcases traditional fishing culture mixed with modern carnival flair in stunning aqua and gold costumes.',
    theme: 'Coastal Heritage',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'freedom-band',
    name: 'Freedom Band',
    description: 'A powerful tribute to African liberation and unity, Freedom Band performs with bold green, black, and gold costumes representing Pan-African pride and cultural strength.',
    theme: 'African Unity',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'masta-blasta-band',
    name: 'Masta Blasta Band',
    description: 'The crowd favorite returns with explosive performances, massive sound systems, and electrifying costumes that light up the night with LED technology and pyrotechnics.',
    theme: 'Electric Dreams',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'diamond-band',
    name: 'Diamond Band',
    description: 'Elegance meets extravagance with Diamond Band\'s crystal-studded costumes, graceful choreography, and sophisticated presentation of Cross River State\'s royal heritage.',
    theme: 'Royal Elegance',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'paradise-band',
    name: 'Paradise Band',
    description: 'A tropical celebration featuring lush green costumes adorned with flowers, birds, and butterflies, representing the biodiversity of Cross River rainforests.',
    theme: 'Tropical Paradise',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'infinity-band',
    name: 'Infinity Band',
    description: 'Pushing boundaries with futuristic costumes and innovative choreography, Infinity Band blends traditional African dance with contemporary performance art.',
    theme: 'Future Forward',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'heritage-band',
    name: 'Heritage Band',
    description: 'Preserving and celebrating the ancient traditions of the Efik, Ejagham, and other Cross River ethnic groups through authentic costumes, masks, and ceremonial dances.',
    theme: 'Ancient Traditions',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'unity-band',
    name: 'Unity Band',
    description: 'A multicultural celebration bringing together performers from across Nigeria and West Africa, showcasing diverse costumes, music, and dance styles in perfect harmony.',
    theme: 'One Africa',
    imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80',
    voteCount: 0,
    year: carnivalYear,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
